### PR TITLE
enable imageupload via ctrl-v

### PR DESCRIPTION
**Pull request by g-user**

### CODE REVIEW

**Comment by turnermm** [comment]
Looks good, but some uploads fail. First we get the green success banner but then the error message saying the upload failed.  I assume this happens because the image is too big.  Do you know the upper limit for this type of upload?

**Comment by g-user** [comment]
No, I didn´t really figured out the upper limit. I was able to upload images up to 70MB without any problems

The main thing that prevents succesful uploading are the php-settings in php.ini, especially the "post_max_size", "upload_max_filesize" and sometimes "memory_limit" are too small. Which settings do you use? 

Often I use the windows microapache-server as a test bench, that comes with the dokuwiki project. There are the standard-sizes of  "post_max_size = 32M", "upload_max_filesize = 15M" and "memory_limit = 128M", that are too small.
For this I use "post_max_size = 256M", "upload_max_filesize = 256M" and "memory_limit = 1024M".

On my (private) production server with ubuntu on odroid-hardware (arm-cpu like raspberry, but more powerful) I have "memory_limit = 512M", "post_max_size = 100M" and "upload_max_filesize = 100M", that works really well.

The other thing with really large images: I saw the javascript-vm size of the browser (firefox) uses 700Mb of memory while uploading. So it depends on the javascript-vm-max-size that the browser can handle. 
My guess for this behaviour is that I used the inherited media_upload procedure from the dokuwiki environment (for security reasons).  With plain php-upload this doesn´t happen (but then the php.ini is the borderline). But uploading files without proper security checking can be risky, so I went this way, that was created and checked by the dokuwiki people that have far more knowledge in security and programming than me.

**Comment by turnermm** [comment]
I tried uploading some image around the 1.95M size and had the problem I described earler despite the fact that I have both post_max_size  and upload_max_filesize set to 8M.  On upping the sizes to something in the double digits, about 35 or 40M, it worked.  Currently ckgedit intercepts images over 2.5M, so to get your results you had to disable or intercept the on paste handler in helper.php.   Which is OK. 

We need a fuller error message than just the red upload failed.  It has to give advice on an upper limit and where to set this up in php.ini, possibly a link or reference to  to the ckgedit plugin page where we can give a fuller explanation under a copy/paste header..

**Comment by g-user** [comment]
Until now I did nothing more than enabling the ckeditor-imageupload-plugin (as described at the ckeditor website) with a minimum of changes of your and the ckeditor-plugin code. 
For my own test I set the value in the helper.php to 250M, it was not in the pull-request, I wanted only demonstrate the possibility. Maybe we can set this value to the value in the php.ini - do you know a method how can one obtain this from php?

Maybe this would be easier for an helpful error message, because it is in your code and we can leave the ckeditor-imageupload-plugin original.
The red "upload failed" error message came from the imageupload-plugin itself. So I have to dig into the plugin where the message is created. Maybe the behavior of "fading out" of the message will be a problem for putting a hyperlink on it...

**Comment by turnermm** [comment]
Dokuwiki uses the $JSINFO global to communicate with javascript.  So in an action class you would do this:
  ```
    global $JSINFO;
     $JSINFO['post_max_size'] = ini_get'['post_max_size];
```
The in your javascript you refer to it without the dollar sign: `JSINFO['post_max_size']` .  I'll get back to you later today or tomorrow.

**Comment by turnermm** [comment]
Yes  we can use the on paste handler that's already there in helper.php, which has a small javascript section.  We could put the reference to the plugin page there together with the documentation for the feature.

**Pull request closed without merging**
