### PR TITLE
Text align syntax (<align %alignment%>...</align>) and WYSIWYG support

### PR DESCRIPTION
**Pull request by jewalky**
subj. Uses "justify" ckeditor plugin.
Initially made it for myself since I needed the functionality, but would be nice if it was added to the upstream.

Oddly enough doesn't support actual justifying because for whatever reason DokuWiki seems to completely ignore text-align:justify in both the editor and the page view.

Also, changed is_ckgeditChrome to detect any chrome version, not just <26, because with non-Chrome "DW edit" button it replaces page contents with \_\_false__ if you choose to discard your edits in Chrome 56.

### CODE REVIEW

**Comment by jewalky** [comment]
Just realized that some things don't work as expected (e.g. it shouldn't be able to apply classes to non-p elements, and it doesn't load lists correctly (although it saves them correctly)). This was ok for my local usage, but definitely not ok for production. Will fix in a bit.

Would still like to know your opinion on whether you can include this if it's fixed or not.

**Comment by turnermm** [comment]
Justify is not part of Dokuwuiki core.  If you need justification you wil have to use a plugin and the native DW editor.  

When you make changes to a file, you should keep everything as it is except for the lines you are changing. Otherwise the diff can become almost useless.

**Comment by turnermm** [comment]
Usurper that the Chrome problem is the result of another plugin.

**Comment by jewalky** [comment]
>Usurper
I suppose that's a quote from some user? Because otherwise it doesn't make sense.

>I suspect that the Chrome problem is the result of another plugin.
It might only happen on the latest DW, which is probably ok since the last confirmed compatible version is the second latest (the Elenor-something).
I have the default installation of DW 2017-02-19a + ckgedit only, no other plugins installed.

>Justify is not part of Dokuwuiki core.
Neither is <font>, but it's added by ckgedit. That's why I thought that adding own syntax for align was ok as well in this case.

>When you make changes to a file, you should keep everything as it is except for the lines you are changing. Otherwise the diff can become almost useless.
So can I make another PR if I fix the issues with diff (sorry for that really, forgot that I applied formatting) and make a plugin with DW-compatible align buttons in ckeditor, or it's a final "no"?

**Comment by turnermm** [comment]
Final no, because Dokuwiki doesn't support justification.  

I checked the Chrome problem and you are right, it's something to do with Chrome + F Manners.  I'll post a temp fix for it in the next few days. And thanks for noticing that the DW link still worked.

**Pull request closed without merging**
