### PR TITLE
Fixed wrong URL to ajax.php when loading GeSHi options (on Nginx)

### LINKED ISSUE #295: Failure of Ajax request in config.js
In config.js.unc, line 238 (respectively in config.js) there is an error in `top.DOKU_BASE + '/lib/exe/ajax.php',`. The URL that is requested is just `http://lib/exe/ajax.php[...]` (the host is missing).

A temporary solution is to replace the `top.DOKU_BASE` by an empty `""`. Otherwise the Editor shows a popup saying "error" and in the browser devtools you can see the failed request to http://lib/...

### PR DESCRIPTION
**Pull request by mdio**
Fixes #295 
I aligned it with how it's being done in config.js.unc:85+.

Works for me with dokuwiki 2017-02-19b and Artic template 2016-09-16.
Thanks to @christianh95 for the pointer.

### CODE REVIEW

**Comment by turnermm** [comment]
First of all, did you have this problem as well?  I've tested on a variety configurations and can't reproduce the problem,  So it would hel pto know what your desktop is and what your server is.

**Comment by mdio** [comment]
Yes, I had the same problem.
Browser: Firefox 53.0 on macOS Sierra 10.12.4
Server: Nginx, but since the call was made to https://lib/exe/ajax.php it wasn't involved in this problem, other then providing the config.js with the ajax call inside.

**Comment by turnermm** [comment]
I ran it on Windows, Centos, and Ubuntu but all use apache.  So it must have something to do with Nginx.

doku_url is already set in config.js.  So, try this:   
    `config.doku_url + 'lib/exe/ajax.php'`
And if it works modify the pull. Thanks.

**Comment by mdio** [comment]
So Nginx is the problem, just as you expected.
top.DOKU_BASE is "/" here.

I adjusted the PR as per your suggestions.

**Comment by taizoli** [comment]
Hello,

i get the same error message. Is there any solution yet?

dokuwiki: 2017-02-19b with bootstrap3 template and apache on linux debian server

**Comment by christianh95** [comment]
@taizoli see first comment in #295, I described a temporary solution

**Comment by turnermm** [comment]
Should be fixed in latest update.

**Pull request merged**
