### PR TITLE
Fix errors in mediamanager

### PR DESCRIPTION
**Pull request by stevenmg**
The media manager window that is opened within the main window was throwing errors and failing to upload media revisions. I added a few extra checks to the mediamanger.php listeners to eliminate these errors.

### CODE REVIEW

**Comment by turnermm** [comment]
I'' try this from the command line just to make sure there are no conflict with recent uploads

**Comment by turnermm** [comment]
I synced my stvg with yours from local copies

**Comment by stevenmg** [comment]
Do you want me to resubmit this on the new repo?

**Comment by turnermm** [comment]
Yes.

**Comment by stevenmg** [comment]
You are right. I'll close this now.

**Pull request closed without merging**
