### PR TITLE
Replace file manager with native DokuWiki file manager

### PR DESCRIPTION
**Pull request by stevenmg**
The default file manager for this plugin is bugged, and is difficult to properly configure for DokuWiki due to how Doku handles images using fetch.php. This PR takes care of that issue by simply using DokuWiki's default file manager which already takes into account features like ACLs which is far more complex using a separate file manager.

### CODE REVIEW

**Comment by turnermm** [comment]
I downloaded you fork and both the link and media browsers return an error message:
`You are not allowed to view this page.`

**Comment by stevenmg** [comment]
Ah, I forgot to change the file browser URL to a relative path so it was directing you to my implementation which is locked down using ACLs. I'll update that. I also found that it is now opening the media manager when I try to insert a link so I will look into that as well.

**Comment by stevenmg** [comment]
Should be working now. Next steps on this would be implementing a good link browser. I don't plan on having time for it until later next week sometime, but I'll send in a PR for that once I get to it.

**Comment by stevenmg** [comment]
I implemented the alignment and link type options from the media manager. Currently size is still ignored and defaults to the original size no matter what is selected in media manager. I am looking into implementing sizes as well.

**Comment by stevenmg** [comment]
I am coming up empty on this one so far. The issue is that CKEditor's Image plugin automatically sets the image size after the dialog is initialized so I cannot simply set the size when I set the other attributes because they will be overridden. The best solution here is probably to modify the default image plugin to make this functionality possible. I will look into this route later.

**Comment by stevenmg** [comment]
Found a somewhat obscured setting to keep the dialog from automatically loading the image size.
`dialog.dontResetSize = true;`
I believe this is ready to merge at this point, but I will be doing more testing of course.

**Comment by turnermm** [comment]
I'm looking forward to how you make out.  It would make a substantial addition to ckgedit if you can get it working. Most of the problems with the current file browser occur with the initial install.

**Comment by stevenmg** [comment]
I am adding the link wizard on this PR as well partially because I broke the old one with this PR and partially because I did everything on master and don't feel like fixing it, haha.

It needs more testing but so far it's working great.

**Comment by stevenmg** [comment]
It looks like there are a few configuration options related to the file browser that will not be working with the default DW file browser. Is it safe to just remove these or will that cause upgrade issues? I'm thinking particularly of people upgrading and their file browser security settings being suddenly loosened. @turnermm

**Comment by turnermm** [comment]
You have to consider that ckgedit is the default WYSIYG editor for Dokuwiki and that it has thousands of users.  I respond to feature requests and bug reports and to my own observations on a regular basis.  So there are frequent upgrades.  When Dokuwiki replaced its own  javascript library with jQuery there was a 3 year breaking-in period during which both were available.  Moreover, there will inevitably be issues that will have to be addressed.  So, for some time, both file browsers will have to be available and users will have to be given a choice.   An IT manager would not want to find out, after a trivial update, that he has suddenly to explain to an office of naive users that there's a big change in their lives.   So, once you've got the kinks worked out,  I'd like to set up a system where with a configuration option users can select their file browser, or perhaps with a button that outputs a cookie---or both.

**Comment by stevenmg** [comment]
Makes sense. Would you see the option being a global option for each implementation, or would you see each user being given the option to select their file browser? Of course if it is per user I would see there being a global setting as well to set which browser(s) are available to the user.

I would think it would be a global setting that, for new implementations would default to DW file browser while upgrades would default to the current file browser. If both are available would we want to push users to use the DW file browser by adding some kind of deprecation note in the configuration if they are using the current file browser?

**Comment by turnermm** [comment]
I think there should be both a global setting made by the admin in the configuration manager and an individual option set by means of a button in the editor.  When the plugin is installed for the first time, a notice will pop up indicating that there is a choice and directing the admin to an explanatory doc on the ckgedit plugin page at dokuwiki.org.  Until the DW file browser's integration into ckgedit has been tested in use, the current file browser would have to remain the default.   I'm sure we will get feedback.

**Comment by stevenmg** [comment]
I added two configuration options (one for which filebrowser(s) to allow and another for which filebrowser should be default. I also added a button for individual users to switch file browsers which is saved in a cookie. Currently files aren't shared between the two browsers though. Any ideas on what needs to be done to get them synced up?

**Comment by turnermm** [comment]
I'm not sure what this lack of sync is about. I'll test your fork and 
see what happens.  They should both open in the current directory.

On 2016-09-06 2:37 PM, Steven Glick wrote:
> Currently files aren't shared between the two browsers though. Any ideas
> on what needs to be done to get them synced up?


---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by turnermm** [comment]
In mediamanager.php line 72:
`        var fileUrl = DOKU_BASE + "data/media/"+  id.replace(/:/g,"/");`
instead of
`var fileUrl = DOKU_BASE + \'/lib/exe/fetch.php/\' + alignleft + id;`
Otherwise the link to the image fails and the link tool window shows a broken image.

Also, I would like to re-instate the original unix-style route to the media directory through the symlinks in fckeditor/userfiles, for backward compatibility.

**Comment by stevenmg** [comment]
in fckeditor/editor/filemanager/connectors/config.php it looks like media folder is set to /data/media by default for windows servers but /userfiles on nix servers. Is there a reason for this? Could we simply use /data/media for everything?

**Comment by turnermm** [comment]
First, a movie clip to show what happens when attempting to insert an image using the DW filebrowser:
   https://www.youtube.com/watch?v=z-Zbd_CdhXM
Notice that the URL box shows that the link tool is trying to access the image using fetch.php, but that isn't a valid url.  It should be one of:
```
/devel/lib/plugins/ckgedit/fckeditor/userfiles/image/keyboard_full.png
/devel/data/media/keyboard_full.png 
```
depending on whether the nix or the windows style access is being used.

There is probably no structural reason why userfiles is needed.  However, there is a question of backward compatibility.  The Windows style needs an .htaccess in the media directory which allows browser access to images, otherwise the images don't display in the filebrowser.  So, windows users are already doing this. But nix are not.  There would be a lot of unhappy campers when they find their filebrowser is broken because we have removed userfiles.  But inserting the proper .htaccess in data/media can be automated when the plugin loads, and I have recently begun doing this when nix users choose the winstyle option.

**Comment by stevenmg** [comment]
Using fetch.php is how media files are meant to be accessed in DokuWiki. This is how DW handles image size constraints and caching. The issue here I believe lies in the fact that I have nice URLs turned on in my implementation which changes the fetch.php parameters. I updated it to use the standard syntax which should fix the issue. This is also compatible with nice URLs.

Currently images inserted via CKGEdit are being retrieved at full size and simply being limited in size via html/css (I haven't bothered to look which). Using fetch.php improves load times by limiting the size of the actual file retrieved. I think we should stick to using fetch.php if at all possible because of this.

As for media files not being in sync, do I understand correctly thinking that using the winstyle option would put all files in one location and in doing so fix the sync issue? Should we simply force winstyle if using both browsers? I'll do some testing.

**Comment by stevenmg** [comment]
Enabling winstyle does seem to do the trick, but as you said I get 403 errors unless I copy over .htaccess manually. Would you see forcing winstyle as being a good solution if both file browsers are enabled? Of course it would need to be clearly communicated in the config, and no defaults would be changed.

**Comment by turnermm** [comment]
>  I updated it to use the standard syntax which should fix the issue. This is also compatible with nice URLs.

Very nice.  
> Would you see forcing winstyle as being a good solution if both file browsers are enabled? 

Yes.

You make a very good case for eventually switching over entirely to the DW filebrowser, once everything is in place.   Because there are relatively frequent updates, it could be done in stages giving users at first the option of trying out the new system and providing notices when an update is installed.

**Comment by turnermm** [comment]
At present, there is a bit of a sync problem with the image size. The link tool picks up the positioning correctly.  But the image size is not in sync with Dokuwiki's, that is,  Dokuwik sets a small image at 100px wide but the in ckgedit using the DW filebrowser it shows up as 200px.   If you click the reset size gizmo, the image size boxes are updated to the original width and height.

**Comment by stevenmg** [comment]
I take back what I said about CKGEdit not using fetch.php. After insert the image is loaded from fetch.php. The only time it is accessed directly is in the insert dialogs. I didn't dig into that as thoroughly as I should have before speaking.

**Comment by stevenmg** [comment]
I am aware of the image sizing issues, and I am working on it. Would you see the reset button setting it to original or setting it to whatever the user selected on insert? Having it set to original was my intent as well as being the default behavior.

**Comment by turnermm** [comment]
>  After insert the image is loaded from fetch.php. The only time it is accessed directly is in the insert dialogs.

Ye, that's true, because ckgedit simply converts the html back to markup and then the markup is read from the file by the parser both when it is displayed in the browser and in the editor.   However, the images uploaded using the ckgedit filebrowser are not recorded in the metadata. Those uploaded using the DW filebrowser are.  So that's a great plus with this upgraded system.

As for the image reset button, re-setting to the original size is fine.

**Comment by stevenmg** [comment]
I added the CKG file browser back as the file browser if DW is selected as the media browser to avoid breaking anything in some more customized implementations where it might be needed.

**Comment by stevenmg** [comment]
How should we approach the link browser? As of now I switched the filebrowser with DWs linkwiz because I had removed file browser, but now that file browser is back we could switch that back to how it was. Personally I like the linkwiz a lot better, but should we switch it hand in hand with the file browser? Do you think it's good as is? I'm thinking it might be best to call that a separate project at this point.

**Comment by turnermm** [comment]
Preferably we should have the native Dokuwiki apps together.  

But this raises an issue we haven't considered yet.  The Dokuwiki media manager is in fact a "media" manager, which means that you can upload zip files, pdf, etc.  But the CKEditor has two toolbar apps (or dialogs), one for images and the other for any other type of file, including types such as pdf, which the Dokuwiki media manager handles. So, when I connected the ckgedit's filebrowser to these dialogs,  I separated out images from all other file types.  The current link dialog handles all file types except for images.  The image dialog handles only images.  This means that if a user uploads a non-image file to the media manager and attempts to insert it into the document, the insertion will fail and the image dialog will show a broken image.

**Comment by stevenmg** [comment]
Ok, let me confirm that I'm understanding you correctly. Currently the link dialog is used to handle not only wiki page links, but also file attachments in general?

If so I could reinstate the old file browser for the link dialog. It seems kind of like a hack since DokuWiki by default doesn't really handle any file attachments other than media. Maybe we could add a third dialog for attachments?

**Comment by turnermm** [comment]
On the DWside the "internal link" selection should and does bring up the linkwiz and accesses data/pages.  On the ckgedit side, it  should for the time being being up the ckgedit filebrowser.  
link_dialog
 When you select "internal media" it accesses the data/media directory.  I'm not convinced we should go for a third dialog (here we are talking about the DW mode).  I think it could be done with jQuery by attaching either a new class or onclick function to each item in the DW media browser which is not an image.  Either we could disable the link or pop-up a message saying that the link dialog must be used to insert non-images.  One of the uses of the "internal media" selection is that it makes it possible to create links to images instead of inserting the images into the text. 

Attached is a version of mediamanager.php which substitutes a message for non-image files in the media manager.
[mediamanager.zip](https://github.com/turnermm/ckgedit/files/462978/mediamanager.zip)

**Comment by turnermm** [comment]
The above means, of course, that we would have to retain the current ckgedit filebrowser to insert non-image media files.  Maybe, as you suggest we could have a third dialog to insert those into one's documents.  Because once this is all straightened away, it would be best to get rid of the current ckgedit filebrowser altogether.

**Comment by stevenmg** [comment]
I am thinking about it some more, and I don't think there's any reason we couldn't use DW media manager for both media links and images. Of course the mediamanager.php script would need to be modified to detect how the dialog was opened (maybe add a URL parameter) and handle the insert accordingly. For images we would need to bypass the dialog that prompts the user for size, alignment, etc, but that could be done with jQuery if not via configuration. Configuration would be preferable of course so I will dig into it.

**Comment by stevenmg** [comment]
Also, I'm giving you edit rights on my fork so if you have anything to add go for it.

**Comment by stevenmg** [comment]
Realized that the media manager actually has an option to set a function to call on insert via a url parameter. I updated mediamanager.php and script.js to use that rather than the current hackish method.

**Comment by turnermm** [comment]
Added preventDefault to image upload finish if upload is not an image.  In mediamanager.php.  
See https://github.com/stevenmg/ckgedit/commit/fb8d5adec594ccfd2a4d3a4a84d790dc13dbb885

**Comment by stevenmg** [comment]
That breaks non image uploads in the media manager across the board. We need it to only break when being called for image inserts. Also I noticed that after an upload the images reload and the jquery script would need to be rerun to keep users from selecting them.

**Comment by turnermm** [comment]
> That breaks non image uploads in the media manager across the board. . . . Also I noticed that after an upload the images reload and the jquery script would need to be rerun to keep users from selecting them.

I'm aware of these issues.  But the first could possibly be handled in the Query string or a cookie set in the link dialog.  As for the second, I  haven't found yet where the media manager updates after the user  clicks 'Done', which is when the non-image links are made active.

**Comment by stevenmg** [comment]
> the first could possibly be handled in the Query string or a cookie set in the link dialog

It might need to be a cookie, I think it is operating in the context of the ajax call so $_GET[] has nothing of value.

> As for the second, I haven't found yet where the media manager updates after the user clicks 'Done', which is when the non-image links are made active.

So far my best lead is https://www.dokuwiki.org/devel:event:html_uploadform_output . If I understand what this does correctly we might even be able to limit the upload form to specific file types on the form itself.

**Comment by stevenmg** [comment]
Actually jQuery could do this quite well. http://api.jquery.com/ajaxComplete

Not sure though if this would be called before or after the main handler that would add the images to the DOM. I'll test it out.

**Comment by stevenmg** [comment]
That's working. One other thing that needs to be done is the linkonly option should be removed for image insert, and the size/alignment dialog shouldn't show for link inserts.

**Comment by stevenmg** [comment]
And that's done. Nothing is coming to mind other than configuration and loose ends. If you think of anything let me know or go ahead and make changes. I am going to keep testing, and I'll try to push this out to a small production implementation I oversee in the next week or so for some more regular testing.

**Comment by turnermm** [comment]
I just added a language string to show why a non-image file doesn't upload ("Upload only images when using image dialog:")

I also discovered that a cookie was the way to go, that the query string was inaccessible, but was away most of the day.

**Comment by turnermm** [comment]
You've done wonders.  I've been working on some version of this plugin for about [10 years](https://www.dokuwiki.org/plugin:ckgedit#history), and I've had the occasional bit of help.  But this is a major contribution.

**Comment by turnermm** [comment]
I just created a branch which syncs your upgrades with edits that had taken place while you were working on the project:
https://github.com/turnermm/ckgedit/tree/stvg
Uncompressed .js files are now `<file>.js.unc`.  All the javascript file destined for downloading are now .js, so to make any further edits you will have to rename the files.

**Comment by stevenmg** [comment]
> I just added a language string to show why a non-image file doesn't upload ("Upload only images when using image dialog:"). But this probably could be stated more clearly:

Awesome. I have been noticing random strings that should be localized here and there so moving forward I'll try to add those as I notice them. As for stating it more clearly, I agree it could be a little unclear, but I don't have a better idea at this point.

> You've done wonders. I've been working on some version of this plugin for about 10 years, and I've had the occasional bit of help. But this is a major contribution. 

Happy to help. For my DokuWiki instance I needed a WYSIWYG editor, and CKGEdit worked well, but the file browser was a point of frustration. You can expect me to be contributing some more as I find issues or improvements to be made.

> I just created a branch which syncs your upgrades with edits that had taken place while you were working on the project

Awesome. I'm happy to see that this project is being actively maintained!

**Comment by turnermm** [comment]
My stvg branch has all the latest updates.  I noticed that you reverted in parse_wiki.js.unc  back to 
`  if(document.cookie.split('ckgFbOpt=')[1].split(';')[0] == 'dokuwiki') {`
--line  if(getCookie('ckgFbOpt') == 'dokuwiki') {

from:
` if(getCookie('ckgFbOpt') == 'dokuwiki') {`

They accomplish the same thing but I just want to keep my version consistent with yours.

**Comment by stevenmg** [comment]
Hmm, not sure why I had done that, but yes I'd think both should behave the same so I see no issue either way.

Should this thread be kept open for discussion for now? I'll make sure I rebase to the stvg branch to avoid any more issues like this.

**Comment by turnermm** [comment]
The dw<=>ckgedit switching mechanism in mine hasn't kept up with your, so I'll fix that today.

**Comment by turnermm** [comment]
Yes, I think we should keep this open until my switching problem is solved.

**Comment by stevenmg** [comment]
I am not seeing anything off hand that is missing in your branch. What issues are you running into?

**Comment by turnermm** [comment]
I've re-synced my stvg branch with yours and everything seems to be working now.  So, you should give the current stvg a quick test.  Then I'll close this discussion.  I see that you have now integrated the media files into the link dialog for the DW mode.  I like that a lot and if all goes well,  this could mean that we can dispense altogether with the old FCKEditor file browser after a bit of use.  And I'll merge stvg version into the master.

**Comment by stevenmg** [comment]
It's working for me.

**Comment by stevenmg** [comment]
I'm going to close this and update my fork to the latest version

**Pull request closed without merging**
