### PR TITLE
JS error when running DokuWiki with ckgedit in an iframe #250

### PR DESCRIPTION
**Pull request by waschinski**
This changeset makes ckgedit compatible with a DokuWiki installation used within an iframe.

### CODE REVIEW

**Comment by turnermm** [comment]
I will assume that this works with the filebrowser?  Before it can be included in a final distribution, it would have to  be tested in ckgdoku and in the farms branches of both ckgedit and ckgdoku.  I'm not familiar with the behavior of  self and would need assurances that it would not cause a cross-site scripting error, particularly in farms.  Otherwise, we could create an entry on the plugin page that explains the use of this in frames.

**Comment by waschinski** [comment]
I added the changes to ckgdoku and it didn't cause any errors when activating it instead of ckgedit.

Not sure how these changes would affect farms at all but I couldn't set it up as of now.

> The _Window.self_ read-only property returns the window itself, as a WindowProxy. It can be used with dot notation on a window object (that is, _window.self_) or standalone (_self_). The advantage of the standalone notation is that a similar notation exists for non-window contexts, such as in Web Workers. By using _self_, you can refer to the global scope in a way that will work not only in a _window_ context (_self_ will resolve to _window.self_) but also in a worker context (_self_ will then resolve to _WorkerGlobalScope.self_).
[Source](https://developer.mozilla.org/de/docs/Web/API/Window/self)

**Comment by turnermm** [comment]
I hope you haven't given up on this.  I have finally come up with a solution that satisfies my paranoia, though I believe you are in fact correct, that changing  to `window.self` would not cause any harm and may in fact be  better. What I've done instead, however, is to create a new variable, `browser_level`, which is assigned to `window.self` when in an iframe or other situation where ` top != window.self`.  Otherwise it is assigned to `top`.  Please try it out:

https://github.com/turnermm/ckgedit/archive/iframe.zip

If this works for  you, I will include it in the  master, and it will make it easy to keep current with ckgedit.

**Comment by waschinski** [comment]
Thanks for getting back to me on this issue, I honestly didn't expect that anymore. ;)

Your solution really sounds like it would be the safer way, making sure not to break farms which I never got to setup in order to test. Anyway, I just dropped your fix in my dev environment and did some more testing. I had to fix two things to make it work for me:

1. In _config.js.unc_ (and _config.js_ accordingly) you missed one use of **top** at line 117. I just replaced it with the new variable **browser_level**.

2. In _edit.php_ at lines 602 and 609 function handlekeypress is being called on **parent** which in an iframe implementation is **windows** instead of **window.self**. I previously must have missed this and now fixed it by adding the same variable as you did in _config.js(.unc)_ and replaced **parent** with it.

`var browser_level = (window.top != window.self) ? window.self : window.top; 
browser_level.handlekeypress(evt);`

After these changes everything looks fine and I couldn't reproduce any JS errors anymore.

**Comment by turnermm** [comment]
Thanks.  I'll make the changes and get back to you, and when all is set I'll merge this into the mast.

**Comment by turnermm** [comment]
I've added your updates to the iframe branch and inserted a small debugging item in helper.php::handlekeypress (lines 201-211).  To test, open the console window and with each keystroke and some mouse clicks you should see `TextChanged <n>`.  Once your tests are complete, you can discard this helper,php and go back to the prervious version.  This new one is different only in the debugging. code.

https://github.com/turnermm/ckgedit/archive/iframe.zip

Thanks,
Myron

**Comment by waschinski** [comment]
Thanks a lot for providing this version which is working fine within an iframe. No more errors regarding calls on **handlekeypress** and the debug messages were showing like you said.

Looking forward to its inclusion in the master, this will really make updating much easier. Thanks again for getting back to this issue!

Regards,
Andreas

**Comment by turnermm** [comment]
Merged the  fix into master. You'll probably get a message about it from github,   Thanks for your help.

**Pull request closed without merging**
