### PR TITLE
Fixes when copying text and images and a new functions

### PR DESCRIPTION
**Pull request by marcoconstancio**
Greetings,

Currently I'm testing dokuwiki with ckgedit to store my notes. I do a lot of copy paste from sites with images and I found it generated errors in certain situations. I also added a function to save remote images on dokuwiki.

My skill in php are a little rusted, so the code might no be the best but if you want add the project, it would be nice. I added more information on the comments of each commit.

Even if you don't add it, thank you for this great plugin.

### CODE REVIEW

**Comment by turnermm** [comment]
Ckgedit can embed images such as the above, with copy and paste.  For instance:
https://www.mturner.org/devel/playground/imagepaste

**Comment by marcoconstancio** [comment]
> Ckgedit can embed images such as the above, with copy and paste. For instance:
> https://www.mturner.org/devel/playground/imagepaste

It can embed images but it only works when when **only** copying a image. When copying a page with text and several images, the parameters are strip out a

 The same thing happens for the data attributes. If a image has multiple data attributes, no error ocurs, but when copying text and images,

**Comment by marcoconstancio** [comment]
Ckgedit can embed images such as the above, with copy and paste. For instance:
https://www.mturner.org/devel/playground/imagepaste

It can embed images but it only works when when only copying a image. When copying a page with text and several images, the parameters are strip out and the images do not work.

The same thing happens for the data attributes. If a image has multiple data attributes, no error occurs, but when copying text and images, it occurs.

**Comment by turnermm** [comment]
I've created a new branch which patches your changes into ckgedit, which I'd like to use for testing:                  https://github.com/turnermm/ckgedit/archive/remote_img.zip
Could you give me a few links to the kinds of pages you are concerned with, pages having text with embedded images with parameters.

### action/save.php
Also, perhaps you could think about a way to encapsulate your code in `action/save.php`  I am  concerned about potential side-effects,  the wide-open character of the regular expression:
     `$re = '/\{\{(https|ftp|http)(.*?)\}\}/ms';`
There are many uses of the ` {{. . .}}` structure in Dokuwiki, including use by many plugins.  So it would help to add limits,something like: 
   `$re = '/\{\{(https|ftp|http)(.*?)(jpg|jpeg|png|tiff)\}\}/ms';`
It would also be necessary to protect the occurrences of these structures if they appear in code blocks or between NOWIKI tags or the literal character markup characters `%%. . .%%`. 

One way to handle these issues is to isolate the pasted text between opening and closing macros.  An example in save.php is at lines 222ff , the `~~MULTI_PLUGIN_OPEN/CLOSE~~` macros.  

### scripts/parse_wiki
Is it here that you are protecting parameters?  
I have compressed `parse_wiki.js.unc` -> `parse_wiki-cmpr.js`.  The latter is used for production purposes.  If you got to the top of `action/edit.php`, you can set  `$test` to true and this will give you a test button, which when pressed pops up several pre-configured alerts, and you can set you own alerts where needed.  The file is  not saved.

**Comment by marcoconstancio** [comment]
> Could you give me a few links to the kinds of pages you are concerned with, pages having text with embedded images with parameters.

So far the I only tried to copy a pages and this forum is the one that gave me the errors: https://www.geeetech.com/forum/viewtopic.php?t=17038 http://www.geeetech.com/forum/viewtopic.php?f=17&t=17037 but I imagine that more cases one other sites.

> $re = '/\{\{(https|ftp|http)(.*?)\}\}/ms';
> There are many uses of the {{. . .}} structure in Dokuwiki, including use by many plugins. So it would help to add limits,something like:
> $re = '/\{\{(https|ftp|http)(.*?)(jpg|jpeg|png|tiff)\}\}/ms';

I considered putting file extensions on the regex, but i found it unreliable because the url might not contains the extension (like images on forum that i mentioned before this), so I leave the decision to the **media_get_from_URL** function and if it does not find the image, it return false and rest of the function does nothing to the text.

> {{. . .}} structure in Dokuwiki, including use by many plugins

I don't have much experience in dokuwiki plugin development, but plugins that use curly brackets aren't supposed usually like **`{{NAME_OF_PLUGIN.....}}`**  ? the regex find cases like **`{{https.....}}`**, **`{{http.....}}`** and **`{{ftp.....}}`** and this kind of syntax should only used by dokuwiki to display media as indicated [here](https://www.dokuwiki.org/images#dynamic_images). However the code I made uses a http head request, so that can be used to double check if it is an image with the mime type returned by the request and if it is not a image,  we can ignore the mach. Example:

```
if (isset($http->resp_headers['content-type'])) {
	if($http->resp_headers['content-type'] == 'image/jpeg' || $http->resp_headers['content-type'] == 'image/gif' || $http->resp_headers['content-type'] == 'image/tiff'){
		....
	}
}
```

> It would also be necessary to protect the occurrences of these structures if they appear in code blocks or between NOWIKI tags or the literal character markup characters %%. . .%%.
> 
> One way to handle some of these issues is to isolate the pasted text between opening and closing macros. An example in save.php is at lines 222ff , the ~~MULTI_PLUGIN_OPEN/CLOSE~~ macros

I have not considered that. I will try test/check those cases.

> scripts/parse_wiki
> Is it here that you are protecting parameters? (On re-reading above, it seems so)

Yes, it was the first thing that occurred to me, and it feels to me a quick hack, rather than a real solution, but I implemented that way because I didn't know much about your plugin to determine which is the best solution. If you feel there a better solution/place then please advise.

> I have compressed parse_wiki.js.unc -> parse_wiki-cmpr.js. The latter is used for production purposes.

I assumed so, but I don't know which compressor you used so, In the commit comment i mentioned modified the uncompressed version because of that.  Which compressor did you use to create this file ?

> If you got to the top of action/edit.php, you can set $test to true and this will give you a test button, which when pressed pops up several pre-configured alerts, and you can set you own alerts where needed -- in parse_wiki.js.unc. The document is tested not saved. 

Cool. Ok, wil try to use it to test.

**Comment by turnermm** [comment]
I tried my patched version, and using your example pages, I did not get the images to load into the saved ckgedit page.  I then installed your own version of ckgedit, from github, and again I had no success with the images.  I tried both firefox and chrome browsers.

**Comment by marcoconstancio** [comment]
> I tried my patched version, and using your example pages, I did not get the images to load into the saved ckgedit page. I then installed your own version of ckgedit, from github, and again I had no success with the images. I tried both firefox and chrome browsers.

I assuming there was no error, correct ? I assumed the image url was not rewritten and  images were not save to the media manager, correct ?

I tested a little just now and forum gave errors on accessing images and then started give me errors on viewing post. Seem they having issues, I try later, meanwhile testing another example:

- copying the button and some text above the the title **border** in  http://kalsey.com/tools/buttonmaker/  seems to work.

**NOTE:** In dokuwiki configuration settings, what is your value in the **fetchsize** setting ? The **media_get_from_URL** function respects this value and will return false when it can get file or the filesize is bigger than that setting, and my opinion, is the correct behavior, because if the user does not want to download files, the plugin should not ignore this settings.  In my settings, I have 100000000 for testing purposes. Can you check this variable and test it again both links ?

**Comment by turnermm** [comment]
I'm afraid the button doesn't work. 

I leave fetchsize set to , i.e. disabled.  Your code may work for your purposes but in an editor that is aimed at a large general audience, its features have to be simple to use and as much as possible free from side-effects.

**Comment by marcoconstancio** [comment]
> I'm afraid the button doesn't work.
> I leave fetchsize set to 0, i.e. disabled. 

I the button is not saved to media manager with fetchsize set to 0, but even still it should be displayed normal using an external url as source. When you say is don't work, do mean it is no being saved or not being displayed ?

> Your code may work for your purposes but in an editor that is aimed at a large general audience, its features have to be simple to use and as much as possible free from side-effects.

The part of saving remote image is just additional function, like your code for saving base64 for saving bandwidth and not use external links. No sure what you mean in last part. Does this mean you don't integrate your plugin with the way it functions ? do want to want to change in any way ? suggestions ? or you do you think it is no worth the effort ?

**Comment by turnermm** [comment]
The button is preserved on pasting into the editor but corrupted when the page is saved. For some reason it gets converted to a table, and this happens whether I  use your code or not.  The forum images are simply lost altogether.  

> Does this mean you don't integrate your plugin with the way it functions ? 

I'm afraid I don't understand this.

> do want to want to change in any way ?

Ckgedit has had contributions by users, some of them very important.  But, first, they have to work, and they have to work without side-effects; and secondly the results have to be consistent with repeated use.   

Ckgedit is an editor, not a conversion tool;  it can't successfully convert all browser pages to dokuwiki markup.

**Comment by turnermm** [comment]
These are my results trying to copy and paste the button using  your fork.
### In Editor After Paste (but Before Saving):
image-text-before Greebo

### After Saving:
img-text-after Greebo

**Comment by turnermm** [comment]
Perhaps this will help, the output that is sent to the server after saving from your forum example:

[save.txt](https://github.com/turnermm/ckgedit/files/3880655/save.txt)

The button output is a table:

{{http://kalsey.com/tools/buttonmaker/button.php?nolink&80x15}}

| |

||||||| |||||||||[[{{  http://kalsey.com/tools/buttonmaker/close.gif?nolink&|Close this window}}]]||
| | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | |
| | | | | | | | | | | | | | | | | | | |

===== Borders =====

**Pull request closed without merging**
