### PR TITLE
Insertion of french missing texts

### PR DESCRIPTION
**Pull request by Laurent3170**
Hope the process of "Pull request" is correctly done by myself as it's only the second one I do...

### CODE REVIEW

**Comment by turnermm** [comment]
Laurent.  Thank you for your language updates.  Just as a point of information:  only the owner of the repository can merge with the original.  When you insert, you are inserting into  your own forked copy.  Dokuwiki has a translate tool: http://translate.dokuwiki.org/.  But your translations have already been included into the ckgedit master by me.  Thanks again.

**Comment by Laurent3170** [comment]
Thanks for your explanations. Didn't know about the translate tool, will take a look at it.
And thanks for my first successful merged pull request :-)

**Comment by Laurent3170** [comment]
As you seem to be really aware, and not me... May I ask you 2 small questions.
1) when we fork on Github, by default it's only the master branch ? And I need to do local git branch -a for the other ones (see and then checkout)
2) if I want my github fork to grab the new pull requests merged to the original git, I have to do a kind of "git pull" from my github fork, is it possible ?
Thanks

**Comment by turnermm** [comment]
1. When you fork a repo you on github get all the branches, but if you clone that to the command line, then you have to check out all branches (except master):
```
#!/bin/sh
#from: http://stackoverflow.com/questions/67699/how-do-i-clone-all-remote-branches-with-git
git checkout -b $1 origin/$1
git branch
```
2. I'm afraid I'm not an expert on the seecond question. So, I could be wrong, but it doesn;'t seem likely.

**Comment by Laurent3170** [comment]
Thanks :smile:

**Comment by Laurent3170** [comment]
Hi,
The answer of the second question is there https://help.github.com/articles/configuring-a-remote-for-a-fork/ and there https://help.github.com/articles/syncing-a-fork/, which consists in:

- On the local fork copy, add a remote : git remote add upstream https://github.com/turnermm/ckgedit.github
- Get the data : git fetch upstream
- switch to master : git checkout master
- merge with upstream : git merge upstream/master
- Pull to my github fork : git pull

**Pull request merged**
